from __future__ import annotations

BOT_MENU_COMMANDS = [
    ("backend", "Show or switch Codex/Claude backend"),
    ("project", "Choose another project"),
    ("thread", "Choose another thread"),
    ("new", "Create a new thread"),
    ("interrupt", "Interrupt the active backend turn"),
    ("queue", "Queue a message instead of steering"),
    ("model", "Choose model and reasoning effort"),
    ("fork", "Fork current thread"),
    ("limits", "Show account rate limits"),
    ("approvals", "Show pending app-server approvals"),
    ("status", "Show current project and thread"),
    ("doctor", "Run bridge diagnostics"),
    ("help", "Show help"),
]
BOT_COMMANDS = [
    *BOT_MENU_COMMANDS,
    ("start", "Bind this chat and show selection"),
    ("codex", "Switch to Codex backend"),
    ("claude", "Switch to Claude Code backend"),
    ("threadinfo", "Show current thread details"),
    ("rename", "Rename current thread"),
    ("archive", "Archive current or numbered threads"),
    ("unarchive", "Unarchive a thread"),
    ("rollback", "Rollback thread history"),
    ("compact", "Start thread compaction"),
    ("goal", "Get or set thread goal"),
    ("mcp", "Show MCP server status"),
    ("review", "Start a review"),
    ("diff", "Show git diff to remote"),
    ("config", "Show backend config"),
    ("skills", "Show available skills"),
    ("hooks", "Show configured hooks"),
    ("apps", "Show apps"),
    ("plugins", "Show plugins"),
    ("summary", "Show current thread summary"),
    ("history", "Show history; /history all supported"),
    ("images", "List or send images from the latest turn"),
    ("files", "List or send files from the latest turn"),
    ("switch", "Switch Codex account auth.json"),
    ("fast", "Show or set fast service tier"),

    ("stop", "Stop the bridge service"),
]
